version: "3.1"
services:

    db:
        image: mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: DB
            MYSQL_ROOT_USER: #Usuario
            MYSQL_PASSWORD: #Contrase単a
            MYSQL_ROOT_PASSWORD: #Contrase単a
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - ./mysql:/var/lib/mysql
        networks:
            - PI_network

    www:
        build: .
        ports: 
            - "970:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db
        networks:
            - PI_network

    phpmyadmin_users:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - "8400:80"
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: #Contrase単a
            MYSQL_ROOT_PASSWORD: #Contrase単a
        networks:
            - PI_network

    
    uptime-kuma:
        image: louislam/uptime-kuma:1
        container_name: uptime-kuma
        volumes:
            - ./uptime-kuma-data:/app/data
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - '3001:3001'
        restart: always
        networks:
            - PI_network

    proxy:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
        networks:
            - PI_network


    portainer:
        image: portainer/portainer:latest
        volumes:
            - ./data:/data
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - '9000:9000'
        networks:
            - PI_network
            
    netdata:
        image: netdata/netdata
        container_name: netdata
        hostname: example.com # set to fqdn of host
        ports:
            - 19999:19999
        restart: unless-stopped
        cap_add:
            - SYS_PTRACE
        security_opt:
            - apparmor:unconfined
        volumes:
            - ./netdataconfig/netdata:/etc/netdata:ro
            - netdatalib:/var/lib/netdata
            - netdatacache:/var/cache/netdata
            - /etc/passwd:/host/etc/passwd:ro
            - /etc/group:/host/etc/group:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /etc/os-release:/host/etc/os-release:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - PI_network    

volumes:
    persistent:
